# Generated by Django 3.2.8 on 2023-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='urlpic',
            field=models.URLField(null=True),
        ),
    ]
